/*
 * Irisnet API
 * Artificial Intelligence (AI) for image- and video-processing in real-time. This is an interactive documentation where you can quickly look up the endpoints and their schemas, while having the opportunity to try things out for yourself.  In the list below, you can see the available endpoints of the API, which can be expanded by clicking on them. Each expanded endpoint lists the request parameters (if available) and the request body (if available). The request body can list some example bodies and the schema, explaining each model in detail.  Additionally you'll find a 'Try it out' button that allows you to enter your custom parameters and custom body and execute that against the API. <b>Be sure to enter your license key to authorize the requests before using this documentation interactively.</b>  The responses section in the expanded endpoint lists the possible responses with their corresponding status codes. If you've executed an API call it will also show you the response from the server.  Underneath the endpoints you'll find the model schemas. These are the models used for the requests and responses. If you click on the right arrow, you can expand the model and get a description of the model and the model parameters. For nested models, you can keep clicking the right arrow for further details.  Clicking the link below the title at the top of this page opens the [OpenAPI specification](https://swagger.io/specification/) (OAS3) in JSON format. The OAS3 Spec allows the generation of clients in many programming languages. There are several free client generators available that can be used to get started easily.
 *
 * The version of the OpenAPI document: v2
 * Contact: info@irisnet.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.irisnet.java.client;

import de.irisnet.java.ApiException;
import de.irisnet.java.client.model.ApiNotice;
import de.irisnet.java.client.model.LicenseInfo;
import de.irisnet.java.client.model.Pricing;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BalanceEndpointsApi
 */
@Disabled
public class BalanceEndpointsApiTest {

    private final BalanceEndpointsApi api = new BalanceEndpointsApi();

    /**
     * Get the cost of the configuration for a single image.
     *
     * The cost is subtracted from the license key after a successful check-image operation.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCostTest() throws ApiException {
        UUID configId = null;
        Pricing response = api.getCost(configId);
        // TODO: test validations
    }

    /**
     * Get information for the given license key.
     *
     * Get the LicenseInfo schema for the given license key in the authorization header.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getLicenseInfoTest() throws ApiException {
        LicenseInfo response = api.getLicenseInfo();
        // TODO: test validations
    }

    /**
     * Get the cost of the configuration for moving images.
     *
     * The cost is subtracted from the license key after a successful check operation for moving images.  &lt;b&gt;NOTICE: The returned cost is an approximation. The exact cost can only be determined during the check operation.&lt;b&gt;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getVideoCostTest() throws ApiException {
        UUID configId = null;
        Long frames = null;
        Pricing response = api.getVideoCost(configId, frames);
        // TODO: test validations
    }

    /**
     * Get the cost of the configuration for moving images.
     *
     * The cost is subtracted from the license key after a successful check operation for moving images.  &lt;b&gt;NOTICE: The returned cost is an approximation. The exact cost can only be determined during the check operation.&lt;b&gt;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getVideoCost1Test() throws ApiException {
        UUID configId = null;
        Integer fps = null;
        Long duration = null;
        Pricing response = api.getVideoCost1(configId, fps, duration);
        // TODO: test validations
    }

}
