/*
 * Irisnet API
 * Artificial Intelligence (AI) for image- and video-processing in real-time. This is an interactive documentation where you can quickly look up the endpoints and their schemas, while having the opportunity to try things out for yourself.  In the list below, you can see the available endpoints of the API, which can be expanded by clicking on them. Each expanded endpoint lists the request parameters (if available) and the request body (if available). The request body can list some example bodies and the schema, explaining each model in detail.  Additionally you'll find a 'Try it out' button that allows you to enter your custom parameters and custom body and execute that against the API. <b>Be sure to enter your license key to authorize the requests before using this documentation interactively.</b>  The responses section in the expanded endpoint lists the possible responses with their corresponding status codes. If you've executed an API call it will also show you the response from the server.  Underneath the endpoints you'll find the model schemas. These are the models used for the requests and responses. If you click on the right arrow, you can expand the model and get a description of the model and the model parameters. For nested models, you can keep clicking the right arrow for further details.  Clicking the link below the title at the top of this page opens the [OpenAPI specification](https://swagger.io/specification/) (OAS3) in JSON format. The OAS3 Spec allows the generation of clients in many programming languages. There are several free client generators available that can be used to get started easily.
 *
 * The version of the OpenAPI document: v2
 * Contact: info@irisnet.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.irisnet.java.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.irisnet.java.client.model.Callback;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import de.irisnet.java.JSON;

/**
 * BiometricCheckRequestData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class BiometricCheckRequestData {
  public static final String SERIALIZED_NAME_CALLBACK = "callback";
  @SerializedName(SERIALIZED_NAME_CALLBACK)
  @javax.annotation.Nonnull
  private Callback callback;

  public static final String SERIALIZED_NAME_FRONT_IMAGE = "frontImage";
  @SerializedName(SERIALIZED_NAME_FRONT_IMAGE)
  @javax.annotation.Nullable
  private String frontImage;

  public static final String SERIALIZED_NAME_SELFIE_IMAGE = "selfieImage";
  @SerializedName(SERIALIZED_NAME_SELFIE_IMAGE)
  @javax.annotation.Nonnull
  private String selfieImage;

  public static final String SERIALIZED_NAME_MINIMUM_ACCEPTED_AGE = "minimumAcceptedAge";
  @SerializedName(SERIALIZED_NAME_MINIMUM_ACCEPTED_AGE)
  @javax.annotation.Nullable
  private Integer minimumAcceptedAge;

  public static final String SERIALIZED_NAME_DOCUMENT_HOLDER_ID = "documentHolderId";
  @SerializedName(SERIALIZED_NAME_DOCUMENT_HOLDER_ID)
  @javax.annotation.Nullable
  private String documentHolderId;

  public BiometricCheckRequestData() {
  }

  public BiometricCheckRequestData callback(@javax.annotation.Nonnull Callback callback) {
    this.callback = callback;
    return this;
  }

  /**
   * Get callback
   * @return callback
   */
  @javax.annotation.Nonnull
  public Callback getCallback() {
    return callback;
  }

  public void setCallback(@javax.annotation.Nonnull Callback callback) {
    this.callback = callback;
  }


  public BiometricCheckRequestData frontImage(@javax.annotation.Nullable String frontImage) {
    this.frontImage = frontImage;
    return this;
  }

  /**
   * The base64-encoded front image of the document to be checked in either jpg or png file format.
   * @return frontImage
   */
  @javax.annotation.Nullable
  public String getFrontImage() {
    return frontImage;
  }

  public void setFrontImage(@javax.annotation.Nullable String frontImage) {
    this.frontImage = frontImage;
  }


  public BiometricCheckRequestData selfieImage(@javax.annotation.Nonnull String selfieImage) {
    this.selfieImage = selfieImage;
    return this;
  }

  /**
   * The base64-encoded selfie image to be checked in either jpg or png file format.
   * @return selfieImage
   */
  @javax.annotation.Nonnull
  public String getSelfieImage() {
    return selfieImage;
  }

  public void setSelfieImage(@javax.annotation.Nonnull String selfieImage) {
    this.selfieImage = selfieImage;
  }


  public BiometricCheckRequestData minimumAcceptedAge(@javax.annotation.Nullable Integer minimumAcceptedAge) {
    this.minimumAcceptedAge = minimumAcceptedAge;
    return this;
  }

  /**
   * The minimum age in years accepted for a DocumentCheck, if applicable. Defaults to 18 if not specified.
   * @return minimumAcceptedAge
   */
  @javax.annotation.Nullable
  public Integer getMinimumAcceptedAge() {
    return minimumAcceptedAge;
  }

  public void setMinimumAcceptedAge(@javax.annotation.Nullable Integer minimumAcceptedAge) {
    this.minimumAcceptedAge = minimumAcceptedAge;
  }


  public BiometricCheckRequestData documentHolderId(@javax.annotation.Nullable String documentHolderId) {
    this.documentHolderId = documentHolderId;
    return this;
  }

  /**
   * The documentHolderId from a previous successful DocumentCheck.
   * @return documentHolderId
   */
  @javax.annotation.Nullable
  public String getDocumentHolderId() {
    return documentHolderId;
  }

  public void setDocumentHolderId(@javax.annotation.Nullable String documentHolderId) {
    this.documentHolderId = documentHolderId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BiometricCheckRequestData biometricCheckRequestData = (BiometricCheckRequestData) o;
    return Objects.equals(this.callback, biometricCheckRequestData.callback) &&
        Objects.equals(this.frontImage, biometricCheckRequestData.frontImage) &&
        Objects.equals(this.selfieImage, biometricCheckRequestData.selfieImage) &&
        Objects.equals(this.minimumAcceptedAge, biometricCheckRequestData.minimumAcceptedAge) &&
        Objects.equals(this.documentHolderId, biometricCheckRequestData.documentHolderId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(callback, frontImage, selfieImage, minimumAcceptedAge, documentHolderId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BiometricCheckRequestData {\n");
    sb.append("    callback: ").append(toIndentedString(callback)).append("\n");
    sb.append("    frontImage: ").append(toIndentedString(frontImage)).append("\n");
    sb.append("    selfieImage: ").append(toIndentedString(selfieImage)).append("\n");
    sb.append("    minimumAcceptedAge: ").append(toIndentedString(minimumAcceptedAge)).append("\n");
    sb.append("    documentHolderId: ").append(toIndentedString(documentHolderId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("callback");
    openapiFields.add("frontImage");
    openapiFields.add("selfieImage");
    openapiFields.add("minimumAcceptedAge");
    openapiFields.add("documentHolderId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("callback");
    openapiRequiredFields.add("selfieImage");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BiometricCheckRequestData
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BiometricCheckRequestData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BiometricCheckRequestData is not found in the empty JSON string", BiometricCheckRequestData.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BiometricCheckRequestData.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BiometricCheckRequestData` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : BiometricCheckRequestData.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `callback`
      Callback.validateJsonElement(jsonObj.get("callback"));
      if ((jsonObj.get("frontImage") != null && !jsonObj.get("frontImage").isJsonNull()) && !jsonObj.get("frontImage").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `frontImage` to be a primitive type in the JSON string but got `%s`", jsonObj.get("frontImage").toString()));
      }
      if (!jsonObj.get("selfieImage").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `selfieImage` to be a primitive type in the JSON string but got `%s`", jsonObj.get("selfieImage").toString()));
      }
      if ((jsonObj.get("documentHolderId") != null && !jsonObj.get("documentHolderId").isJsonNull()) && !jsonObj.get("documentHolderId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `documentHolderId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("documentHolderId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BiometricCheckRequestData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BiometricCheckRequestData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BiometricCheckRequestData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BiometricCheckRequestData.class));

       return (TypeAdapter<T>) new TypeAdapter<BiometricCheckRequestData>() {
           @Override
           public void write(JsonWriter out, BiometricCheckRequestData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BiometricCheckRequestData read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BiometricCheckRequestData given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BiometricCheckRequestData
   * @throws IOException if the JSON string is invalid with respect to BiometricCheckRequestData
   */
  public static BiometricCheckRequestData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BiometricCheckRequestData.class);
  }

  /**
   * Convert an instance of BiometricCheckRequestData to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

