/*
 * Irisnet API
 * Artificial Intelligence (AI) for image- and video-processing in real-time. This is an interactive documentation where you can quickly look up the endpoints and their schemas, while having the opportunity to try things out for yourself.  In the list below, you can see the available endpoints of the API, which can be expanded by clicking on them. Each expanded endpoint lists the request parameters (if available) and the request body (if available). The request body can list some example bodies and the schema, explaining each model in detail.  Additionally you'll find a 'Try it out' button that allows you to enter your custom parameters and custom body and execute that against the API. <b>Be sure to enter your license key to authorize the requests before using this documentation interactively.</b>  The responses section in the expanded endpoint lists the possible responses with their corresponding status codes. If you've executed an API call it will also show you the response from the server.  Underneath the endpoints you'll find the model schemas. These are the models used for the requests and responses. If you click on the right arrow, you can expand the model and get a description of the model and the model parameters. For nested models, you can keep clicking the right arrow for further details.  Clicking the link below the title at the top of this page opens the [OpenAPI specification](https://swagger.io/specification/) (OAS3) in JSON format. The OAS3 Spec allows the generation of clients in many programming languages. There are several free client generators available that can be used to get started easily.
 *
 * The version of the OpenAPI document: v2
 * Contact: info@irisnet.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.irisnet.java.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import de.irisnet.java.JSON;

/**
 * A list of known faces, describing which other documentHolders match this documentHolder with a certain similarity
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class KnownFace {
  public static final String SERIALIZED_NAME_DOCUMENT_HOLDER_ID = "documentHolderId";
  @SerializedName(SERIALIZED_NAME_DOCUMENT_HOLDER_ID)
  @javax.annotation.Nullable
  private String documentHolderId;

  public static final String SERIALIZED_NAME_FACE_SIMILARITY = "faceSimilarity";
  @SerializedName(SERIALIZED_NAME_FACE_SIMILARITY)
  @javax.annotation.Nullable
  private Integer faceSimilarity;

  public KnownFace() {
  }

  public KnownFace documentHolderId(@javax.annotation.Nullable String documentHolderId) {
    this.documentHolderId = documentHolderId;
    return this;
  }

  /**
   * The id of the documentHolder
   * @return documentHolderId
   */
  @javax.annotation.Nullable
  public String getDocumentHolderId() {
    return documentHolderId;
  }

  public void setDocumentHolderId(@javax.annotation.Nullable String documentHolderId) {
    this.documentHolderId = documentHolderId;
  }


  public KnownFace faceSimilarity(@javax.annotation.Nullable Integer faceSimilarity) {
    this.faceSimilarity = faceSimilarity;
    return this;
  }

  /**
   * Indicates the similarity-level between the known face and the documentHolder&#39;s selfie
   * @return faceSimilarity
   */
  @javax.annotation.Nullable
  public Integer getFaceSimilarity() {
    return faceSimilarity;
  }

  public void setFaceSimilarity(@javax.annotation.Nullable Integer faceSimilarity) {
    this.faceSimilarity = faceSimilarity;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KnownFace knownFace = (KnownFace) o;
    return Objects.equals(this.documentHolderId, knownFace.documentHolderId) &&
        Objects.equals(this.faceSimilarity, knownFace.faceSimilarity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documentHolderId, faceSimilarity);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KnownFace {\n");
    sb.append("    documentHolderId: ").append(toIndentedString(documentHolderId)).append("\n");
    sb.append("    faceSimilarity: ").append(toIndentedString(faceSimilarity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("documentHolderId");
    openapiFields.add("faceSimilarity");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to KnownFace
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!KnownFace.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in KnownFace is not found in the empty JSON string", KnownFace.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!KnownFace.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `KnownFace` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("documentHolderId") != null && !jsonObj.get("documentHolderId").isJsonNull()) && !jsonObj.get("documentHolderId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `documentHolderId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("documentHolderId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!KnownFace.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'KnownFace' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<KnownFace> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(KnownFace.class));

       return (TypeAdapter<T>) new TypeAdapter<KnownFace>() {
           @Override
           public void write(JsonWriter out, KnownFace value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public KnownFace read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of KnownFace given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of KnownFace
   * @throws IOException if the JSON string is invalid with respect to KnownFace
   */
  public static KnownFace fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, KnownFace.class);
  }

  /**
   * Convert an instance of KnownFace to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

